---
- name: Prep VMs for OpenStack
  hosts: all
  user: vagrant
  become: true

  roles:
    - prereqs
    - upgrade
    - networking
    - pip

- name: Run OpenStack Installation
  hosts: controller-01
  user: vagrant
  become: true

  roles:
    - getplaybooks
    - installansible
    - configuredeployment
    - runplaybooks

- name: Reload libvirtd
  hosts: compute-01
  user: vagrant
  become: true

  tasks:
    - command: "systemctl restart libvirtd"

