---
- name: Prep VMs for OpenStack
  hosts: all
  user: vagrant
  become_user: root
  become_method: sudo

  roles:
    - common
    - upgrade
    - prereqs
    - networking

- name: Run OpenStack Installation
  hosts: logging-01
  user: vagrant
  become_user: root
  become_method: sudo

  roles:
    - getplaybooks
    - installansible
    - configuredeployment
    - runplaybooks
