---
- name: Run OpenStack Install
  hosts: logging
  user: vagrant
  become_user: root
  become_method: sudo

  roles:
    - getplaybooks
    - installansible
    - configuredeployment
    - runplaybooks
