---
environment_version: 3511a43b8e4cc39af4beaaa852b5f917
cidr_networks:
  container: 172.16.0.0/16
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - 172.16.0.198,172.16.0.203
  - 172.29.240.198,172.29.240.203

global_overrides:
  internal_lb_vip_address: 172.16.0.201
  external_lb_vip_address: 192.168.100.201
  lb_name: logging
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        type: "raw"
        ip_from_q: "container"
        group_binds:
          - all_containers
          - hosts
    - network:
        container_bridge: "br-vxlan"
        container_interface: "eth10"
        type: "vxlan"
        ip_from_q: "tunnel"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent

infra_hosts:
  controller-01:
    ip: 172.16.0.198
  controller-02:
    ip: 172.16.0.199
  controller-03:
    ip: 172.16.0.200

# User defined Compute Hosts, this should be a required group
compute_hosts:
  compute-01:
    ip: 172.16.0.202
#  compute-02:
#    ip: 172.16.0.203

#storage_hosts:
#  logging:
#    ip: 172.16.0.201
#    container_vars:
#      cinder_backends:
#        limit_container_types: cinder_volume
#        lvm:
#          volume_group: cinder-volumes
#          volume_driver: cinder.volume.drivers.lvm.LVMISCSIDriver
#          volume_backend_name: LVM_iSCSI

log_hosts:
  logging:
    ip: 172.16.0.201

network_hosts:
  controller-01:
    ip: 172.16.0.198
  controller-02:
    ip: 172.16.0.199
  controller-03:
    ip: 172.16.0.200

haproxy_hosts:
  logging:
    ip: 172.16.0.201
