---
- name: Ensure Apt directory exists
  file: path=/etc/apt/apt.conf.d state=directory mode=0755

- name: Apt Proxy Config
  template: src=01squid.j2 dest=/etc/apt/apt.conf.d/01squid.conf owner=root group=root mode=0644

- name: Upgrade Ubuntu Packages
  apt: upgrade=safe update_cache=yes cache_valid_time=3600
